# Autolocalization

## Autolocalization
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS ADD CONTENT
* CMS CLICK PAGE
* CMS ENTER REVISION TAG
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE1
* CMS Enter HTML Content
* CMS CLICK BASIC INFO
* CMS ENTER TITLE
* CMS ENTER ANALYTICS
* CMS SELECT SITE SECTION
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS CLICK LOCALIZE TAB
* CMS SELECT COUNTRY LANGUAGE TO LOCALIZE FROM
* CMS SELECT MULTIPLE LOCALES TO LOCALIZE TO
* CMS ADD REVISION TAG
* CMS SELECT AUTOLOCALIZE OPTION
* CMS CLICK LOCALIZE BUTTON
* CMS CLICK CONTINUE
* CMS VALIDATE AUTOLOCALIZATION SUCCESS MESSAGE
* CMS VALIDATE CONTENT FROM TABLE
* CMS VALIDATE ALL LOCALES FROM TABLE
* CMS SAVE THE DESTINATION NODE
* CMS NAVIGATE TO SOURCE NODE
* CMS CLICK COPY TO NEW DRAFT
* CMS EDIT REVISION TAG
* CMS EDIT HTML CONTENT
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS COPY REVISION TAG
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
//Trigger autolocalize in reports tab
* CMS REPORTS
* CMS CLICK AUTO LOCALIZE
* CMS CLICK RUN AUTO LOCALIZE
//Verify a new published revision is created and displays for the destination node
* CMS VALIDATE THE NEW PUBLISHED REVISION 