# Add SPPRCIS content

## Add SPPRCIS content
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS ADD CONTENT
* CMS CLICK SPPRCIS
* CMS ENTER REVISION TAG
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE1
* CMS ENTER SOME TEXT IN DESCRIPTION
* CMS CLICK ADD ANOTHER ITEM
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE2
* CMS POPULATE LOWER SLOTS
* CMS SELECT PRODUCT FROM PRODUCTTREE
* CMS SELECT FORMATTER TEMPLATE
* CMS CLICK BASIC INFO
* CMS ENTER TITLE
* CMS ENTER ANALYTICS
* CMS SELECT SITE SECTION
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS CLICK ON TITLE TO NAVIGATE TO FRONTEND
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS VALIDATE CONTENT ON FRONTEND
* CMS NAVIGATE TO SPP
* CMS FEEDBACK Popup Close
* CMS LOGOUT FROM CMS
* CMS LAUNCH CONTENT AS AN ANONYMOUS USER
* CMS NAVIGATE TO SPP AS AN ANONYMOUS USER
