# Bulk Localize many to many

## Bulk Localize many to many
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS FIND CONTENT
* CMS CHOOSE CONTENT BLOCK TYPE
* CMS CLICK SELECT FIVE CONTENTS
* CMS SELECT LOCALIZE FROM UPDATE MULTIPLE ITEMS AT ONCE
* CMS CLICK UPDATE
* CMS SELECT MULTIPLE COUNTRIES-LANGUAGES TO LOCALIZE TO
* CMS CLICK NEXT OR CONFIRM
* CMS ENTER REVISION TAG TO LOCALIZE CONTENT
* CMS CLICK NEXT OR CONFIRM
* CMS LOCALIZE REFERENCED CONTENT
* CMS VERIFY LOCALIZE SUCCESS MESSAGE AND MULTIPLE LOCALES IN SUCEESS MESSAGE
* CMS VALIDATE LOCALES FROM TABLE