# Clone from find content

## Clone from find content
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS FIND CONTENT
* CMS CHOOSE TYPE
* CMS SELECT WORKFLOW STATE
* CMS CLICK FILTER
* CMS CLICK CLONE
* CMS CLICK YES CLONE THIS CONTENT
* CMS EDIT REVISION TAG
* CMS CLICK BASIC INFO
* CMS EDIT ANALYTICS
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS COPY REVISION TAG
* CMS VALIDATE CONTENT IS A CLONE
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS PUBLISH SUCCESS MESSAGE
* CMS VERIFY PUBLISHED STATUS