# Disable Autolocalization

## Disable Autolocalization
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS FIND CONTENT
* CMS AUTOLOC ENABLED SEARCH
* CMS AUTOMATIC LOCALIZATION COUNTRY FROM
* CMS AUTOMATIC LOCALIZATION COUNTRY TO
* CMS CLICK FILTER
* CMS CLICK ON WORKFLOW
* CMS CLICK LOCALIZE TAB
* CMS VERIFY AUTOLOCALIZE IS ENABLED FOR SELECTED LOCALE
* CMS FIND CONTENT
* CMS AUTOLOC ENABLED SEARCH
* CMS AUTOMATIC LOCALIZATION COUNTRY FROM
* CMS AUTOMATIC LOCALIZATION COUNTRY TO
* CMS CLICK FILTER
* CMS SELECT FILTERED CONTENT
* CMS SELECT LOCALIZE FROM UPDATE MULTIPLE ITEMS AT ONCE
* CMS CLICK UPDATE
* CMS SELECT A COUNTRY LANGUAGE TO DISABLE AUTOLOCALIZE
* CMS SELECT DISABLE AUTOLOCALIZE OPTION
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS VERIFY DISABLE AUTOLOCALIZE SUCCESS MESSAGE
* CMS FIND CONTENT
* CMS AUTOLOC ENABLED SEARCH
* CMS AUTOMATIC LOCALIZATION COUNTRY FROM
* CMS AUTOMATIC LOCALIZATION COUNTRY TO
* CMS CLICK FILTER
* CMS CLICK ON WORKFLOW
* CMS CLICK LOCALIZE TAB
* CMS VERIFY AUTOLOCALIZE IS DISABLED FOR SELECTED LOCALE