# Find content bulk

## Find content bulk
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS FIND CONTENT
* CMS CHOOSE WORKFLOW STATE
* CMS CLICK FILTER
* CMS CLICK SELECT FIVE CONTENTS
* CMS SELECT BULK OPERATION "Approve"
* CMS CLICK UPDATE
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK APPROVE SUCCESS MESSAGE
* CMS CLICK SELECT ALL CHECKBOX
* CMS SELECT BULK OPERATION "Unapprove"
* CMS CLICK UPDATE
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK UNAPPROVE SUCCESS MESSAGE
* CMS CLICK SELECT ALL CHECKBOX
* CMS SELECT BULK OPERATION "Approve"
* CMS CLICK UPDATE
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK APPROVE SUCCESS MESSAGE
* CMS CLICK SELECT FIVE CONTENTS
* CMS SELECT BULK OPERATION "Publish"
* CMS CLICK UPDATE
* CMS CLICK PUBLISH CONFIRMATION
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK PUBLISH SUCCESS MESSAGE
* CMS CLICK SELECT FIVE CONTENTS
* CMS SELECT BULK OPERATION "Unpublish"
* CMS CLICK UPDATE
* CMS CLICK UNPUBLISH CONFIRMATION
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK UNPUBLISH SUCCESS MESSAGE
* CMS CLICK SELECT FIVE CONTENTS
* CMS SELECT BULK OPERATION "Republish"
* CMS CLICK UPDATE
* CMS CLICK PUBLISH CONFIRMATION
* CMS ENTER BULK LOG MESSAGE
* CMS CLICK NEXT OR CONFIRM
* CMS CLICK NEXT OR CONFIRM
* CMS BULK PUBLISH SUCCESS MESSAGE
