# Localize one to one

## Localize one to one
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS ADD CONTENT
* CMS CLICK PAGE
* CMS ENTER REVISION TAG
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE1
* CMS Enter HTML Content
* CMS CLICK BASIC INFO
* CMS ENTER TITLE
* CMS ENTER ANALYTICS
* CMS SELECT SITE SECTION
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS CLICK LOCALIZE TAB
* CMS SELECT COUNTRY LANGUAGE TO LOCALIZE FROM
* CMS SELECT 1 LOCALE TO LOCALIZE TO
* CMS ENTER REVISION TAG
* CMS CLICK LOCALIZE BUTTON
* CMS VALIDATE LOCALIZATION SUCCESS MESSAGE
* CMS VALIDATE CORRECT CONTENT IS LOCALIZED
* CMS VALIDATE LOCALE