# Revision tag functionality

## Revision tag functionality
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS ADD CONTENT
* CMS CLICK PAGE
* CMS ENTER REVISION TAG
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE1
* CMS Enter HTML Content
* CMS CLICK BASIC INFO
* CMS ENTER TITLE
* CMS ENTER ANALYTICS
* CMS SELECT SITE SECTION
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS CLICK ON TITLE TO NAVIGATE TO FRONTEND
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS VALIDATE CONTENT ON FRONTEND
* CMS NAVIGATE TO WORKFLOW PAGE
* CMS CLICK COPY TO NEW DRAFT
* CMS EDIT HTML CONTENT
* CMS EDIT REVISION TAG
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS COPY REVISION TAG
* CMS NAVIGATE TO ORIGINAL CONTENT ON FE
* CMS FEEDBACK Popup Close
* CMS VALIDATE CONTENT ON FRONTEND
* CMS SELECT NEW CONTENT FROM REVISION TAG
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS VALIDATE THE NEW CONTENT