# Workflow status

## Workflow status
* CMS Initialize Helix
* CMS Configuring the prerequisites like set cookies, revision tag
* CMS Open CMS Website
* CMS CookieRejectButton
* CMS FEEDBACK Popup Close
* CMS Popup Close
* CMS Login to CMS as a test User
* CMS Login User Name
* CMS Login Password
* CMS Login Button
* CMS ADD CONTENT
* CMS CLICK PAGE
* CMS ENTER REVISION TAG
* CMS EXPAND TO ADD NEW ITEM
* CMS SELECT LAYOUT TEMPLATE1
* CMS Enter HTML Content
* CMS CLICK BASIC INFO
* CMS ENTER TITLE
* CMS ENTER ANALYTICS
* CMS SELECT SITE SECTION
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS DRAFT SUCCESS MESSAGE
* CMS VERIFY DRAFT STATUS
* CMS CLICK WORKFLOW "Edit"
* CMS SAVE & CHANGE WORK FLOW STATUS
* CMS UPDATED SUCCESS MESSAGE
* CMS VERIFY DRAFT STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS APPROVE SUCCESS MESSAGE
* CMS VERIFY APPROVED STATUS
* CMS CLICK WORKFLOW "Unapprove"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS UNAPPROVE SUCCESS MESSAGE
* CMS VERIFY DRAFT STATUS
* CMS CLICK WORKFLOW "Approve"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS APPROVE SUCCESS MESSAGE
* CMS VERIFY APPROVED STATUS
* CMS CLICK WORKFLOW "Publish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS PUBLISH SUCCESS MESSAGE
* CMS VERIFY PUBLISHED STATUS
* CMS CLICK WORKFLOW "Unpublish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES UNPUBLISH THIS CONTENT
* CMS UNPUBLISH SUCCESS MESSAGE
* CMS VERIFY UNPUBLISHED STATUS
* CMS CLICK WORKFLOW "Republish"
* CMS ENTER LOG MESSAGE
* CMS CLICK UPDATE STATE
* CMS CLICK YES PUBLISH THIS CONTENT
* CMS PUBLISH SUCCESS MESSAGE
* CMS VERIFY PUBLISHED STATUS
